[tool.ruff]
# Включить дополнительные наборы правил (например, для isort, pyupgrade)
select = ["E", "F", "B", "I"]
# Исключить директории (например, сгенерированные файлы или venv)
exclude = [
    ".git",
    "__pycache__",
    "venv",
]

[tool.ruff.format]
# Настройки для форматера, например:
line-length = 120