[tool.ruff]
#line-length = 120
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "asd",
]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A"]


[tool.pyright]
venvPath = "."
venv = ".venv"