[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "experiments.py",
]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A"]


[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [".venv", "experiments.py"]