[tool.ruff]
line-length = 120

exclude = [
    ".git",
    "__pycache__",
    ".venv",
]

[tool.ruff.lint]
select = ["E", "F", "B", "I"] # Включить дополнительные наборы правил (например, для isort, pyupgrade)
#ignore = ["E501"]